import type { MergeConflictEncounter } from '../types';

export const SEED_CONFLICTS: MergeConflictEncounter[] = [
    {
        id: 'mc-react-hooks',
        title: 'The Great Hook Conflict',
        description: 'Two PRs modified the same useEffect. One adds a cleanup, the other changes the dependency array. Choose wisely.',
        difficulty: 2,
        timeLimit: 30,
        districtId: 'react-district',
        reward: 500,
        hunks: [
            {
                id: 1,
                label: 'Add cleanup function',
                code: 'useEffect(() => {\n  subscribe(channel);\n  return () => unsubscribe(channel);\n}, [channel]);',
                side: 'ours',
            },
            {
                id: 2,
                label: 'Fix dependency array',
                code: 'useEffect(() => {\n  subscribe(channel);\n}, [channel, userId]);',
                side: 'theirs',
            },
            {
                id: 3,
                label: 'Combined fix',
                code: 'useEffect(() => {\n  subscribe(channel);\n  return () => unsubscribe(channel);\n}, [channel, userId]);',
                side: 'resolved',
            },
        ],
        correctOrder: [3],
    },
    {
        id: 'mc-rust-lifetimes',
        title: 'Lifetime Showdown',
        description: 'Two lifetime annotations clash. One borrow checker error blocks everything. Pick the resolution that compiles.',
        difficulty: 3,
        timeLimit: 25,
        districtId: 'rust-docks',
        reward: 600,
        hunks: [
            {
                id: 1,
                label: "Explicit lifetime 'a",
                code: "fn process<'a>(data: &'a str) -> &'a str {\n  &data[1..]\n}",
                side: 'ours',
            },
            {
                id: 2,
                label: 'Owned String return',
                code: 'fn process(data: &str) -> String {\n  data[1..].to_string()\n}',
                side: 'theirs',
            },
            {
                id: 3,
                label: 'Clone with lifetime',
                code: "fn process<'a>(data: &'a str) -> String {\n  data[1..].to_string()\n}",
                side: 'resolved',
            },
        ],
        correctOrder: [2],
    },
    {
        id: 'mc-python-imports',
        title: 'Import Collision',
        description: 'Two modules want the same name. Both PRs renamed the import differently. Untangle this mess.',
        difficulty: 1,
        timeLimit: 35,
        districtId: 'python-heights',
        reward: 350,
        hunks: [
            {
                id: 1,
                label: 'Alias import as utils_v1',
                code: 'from legacy import helpers as utils_v1\nfrom modern import helpers as utils_v2',
                side: 'ours',
            },
            {
                id: 2,
                label: 'Remove legacy entirely',
                code: 'from modern import helpers as utils',
                side: 'theirs',
            },
            {
                id: 3,
                label: 'Keep both with clear aliases',
                code: 'from legacy import helpers as legacy_utils\nfrom modern import helpers as utils',
                side: 'resolved',
            },
        ],
        correctOrder: [3],
    },
    {
        id: 'mc-ts-types',
        title: 'Type War at the Terminal',
        description: 'A union type and an intersection type can\'t agree. Two PRs are fighting over the interface definition.',
        difficulty: 4,
        timeLimit: 20,
        districtId: 'typescript-terminal',
        reward: 700,
        hunks: [
            {
                id: 1,
                label: 'Union type approach',
                code: 'type Config = BaseConfig | ExtendedConfig;\n\nfunction init(cfg: Config) {\n  if ("extended" in cfg) { /* ... */ }\n}',
                side: 'ours',
            },
            {
                id: 2,
                label: 'Intersection type approach',
                code: 'type Config = BaseConfig & Partial<ExtendedConfig>;\n\nfunction init(cfg: Config) {\n  if (cfg.extended) { /* ... */ }\n}',
                side: 'theirs',
            },
            {
                id: 3,
                label: 'Discriminated union',
                code: 'type Config = \n  | { kind: "base" } & BaseConfig\n  | { kind: "extended" } & ExtendedConfig;\n\nfunction init(cfg: Config) {\n  if (cfg.kind === "extended") { /* ... */ }\n}',
                side: 'resolved',
            },
        ],
        correctOrder: [3],
    },
    {
        id: 'mc-go-channels',
        title: 'Channel Deadlock',
        description: 'Two goroutine patterns are competing. One causes a deadlock. Pick the safe pattern before the Freeway crashes.',
        difficulty: 3,
        timeLimit: 25,
        districtId: 'go-freeway',
        reward: 550,
        hunks: [
            {
                id: 1,
                label: 'Unbuffered channel',
                code: 'ch := make(chan int)\ngo func() { ch <- 42 }()\nresult := <-ch',
                side: 'ours',
            },
            {
                id: 2,
                label: 'Buffered channel',
                code: 'ch := make(chan int, 1)\nch <- 42\nresult := <-ch',
                side: 'theirs',
            },
            {
                id: 3,
                label: 'Select with timeout',
                code: 'ch := make(chan int, 1)\ngo func() { ch <- 42 }()\nselect {\ncase result := <-ch:\n  fmt.Println(result)\ncase <-time.After(time.Second):\n  fmt.Println("timeout")\n}',
                side: 'resolved',
            },
        ],
        correctOrder: [3],
    },
];
