import type { District } from '../types';

export const SEED_DISTRICTS: District[] = [
    {
        id: 'react-district',
        name: 'React District',
        description: 'The flashiest neighborhood in town. Neon signs re-render every frame. Home to the Chrome Syndicate.',
        color: '#61DAFB',
        emissive: '#00BFFF',
        position: [-30, -30],
        size: [40, 40],
        faction: 'chrome-syndicate',
        heatLevel: 45,
        repoSource: {
            owner: 'facebook',
            repo: 'react',
            language: 'JavaScript',
            stars: 220000,
            openIssues: 900,
            lastActivity: '2026-03-07T00:00:00Z',
        },
        missionIds: ['m-deliver-patch-react', 'm-escape-test-drones', 'm-boss-merge-react'],
    },
    {
        id: 'rust-docks',
        name: 'Rust Docks',
        description: 'Heavy industrial zone. Cargo ships run on zero-cost abstractions. The Rust Collective owns every crane.',
        color: '#FF6B35',
        emissive: '#FF4500',
        position: [30, -30],
        size: [40, 40],
        faction: 'rust-collective',
        heatLevel: 60,
        repoSource: {
            owner: 'rust-lang',
            repo: 'rust',
            language: 'Rust',
            stars: 95000,
            openIssues: 8500,
            lastActivity: '2026-03-07T00:00:00Z',
        },
        missionIds: ['m-recover-artifact-rust', 'm-defend-terminal-rust'],
    },
    {
        id: 'python-heights',
        name: 'Python Heights',
        description: 'Uptown luxury. Everything is dynamically typed and beautifully indented. The Python Cartel runs the penthouses.',
        color: '#FFD43B',
        emissive: '#FFD700',
        position: [-30, 30],
        size: [40, 40],
        faction: 'python-cartel',
        heatLevel: 30,
        repoSource: {
            owner: 'python',
            repo: 'cpython',
            language: 'Python',
            stars: 62000,
            openIssues: 7800,
            lastActivity: '2026-03-07T00:00:00Z',
        },
        missionIds: ['m-deliver-patch-python', 'm-smuggle-hotfix'],
    },
    {
        id: 'go-freeway',
        name: 'Go Freeway',
        description: 'Fast lanes, minimal signage. What you see is what you get. The Go Yakuza keep traffic flowing.',
        color: '#00ADD8',
        emissive: '#00CED1',
        position: [30, 30],
        size: [40, 40],
        faction: 'go-yakuza',
        heatLevel: 20,
        repoSource: {
            owner: 'golang',
            repo: 'go',
            language: 'Go',
            stars: 122000,
            openIssues: 8900,
            lastActivity: '2026-03-07T00:00:00Z',
        },
        missionIds: ['m-race-regression', 'm-defend-terminal-go'],
    },
    {
        id: 'typescript-terminal',
        name: 'TypeScript Terminal',
        description: 'The transit hub. Types are checked at every gate. The Node Mafia controls the railway.',
        color: '#3178C6',
        emissive: '#4169E1',
        position: [0, -60],
        size: [35, 35],
        faction: 'node-mafia',
        heatLevel: 55,
        repoSource: {
            owner: 'microsoft',
            repo: 'TypeScript',
            language: 'TypeScript',
            stars: 99000,
            openIssues: 5600,
            lastActivity: '2026-03-07T00:00:00Z',
        },
        missionIds: ['m-hijack-release', 'm-boss-merge-ts'],
    },
    {
        id: 'linux-underground',
        name: 'Linux Underground',
        description: 'The old city beneath. Ancient tunnels, kernel-level operations. No faction fully controls it. Neutral ground... mostly.',
        color: '#A855F7',
        emissive: '#9333EA',
        position: [0, 60],
        size: [35, 35],
        faction: 'unaligned',
        heatLevel: 75,
        repoSource: {
            owner: 'torvalds',
            repo: 'linux',
            language: 'C',
            stars: 175000,
            openIssues: 300,
            lastActivity: '2026-03-07T00:00:00Z',
        },
        missionIds: ['m-recover-artifact-linux', 'm-escape-test-drones-linux'],
    },
];
