import type { Mission } from '../types';

export const SEED_MISSIONS: Mission[] = [
    // === DELIVERY MISSIONS ===
    {
        id: 'm-deliver-patch-react',
        title: 'Patch Runner: React Hotfix',
        description: 'A critical useState patch needs to reach the deploy terminal before the nightly build. Dodge the linters, avoid the type-checkers, and deliver the goods.',
        type: 'delivery',
        districtId: 'react-district',
        difficulty: 2,
        timeLimit: 45,
        reward: 150,
        factionReward: 10,
        status: 'available',
        objectives: ['Pick up the patch package', 'Reach the deploy terminal', 'Deliver before timeout'],
        waypoints: [
            { id: 'wp-react-d1', label: 'Pick Up Patch', position: [-40, 0.5, -40], radius: 4, order: 0 },
            { id: 'wp-react-d2', label: 'Deploy Terminal', position: [-20, 0.5, -20], radius: 4, order: 1 },
            { id: 'wp-react-d3', label: 'Drop Off', position: [-30, 0.5, -15], radius: 4, order: 2 },
        ],
    },
    {
        id: 'm-deliver-patch-python',
        title: 'Dependency Mule: PyPI Drop',
        description: 'Smuggle a new dependency through Python Heights without triggering the virtual environment scanners.',
        type: 'delivery',
        districtId: 'python-heights',
        difficulty: 1,
        timeLimit: 60,
        reward: 100,
        factionReward: 8,
        status: 'available',
        objectives: ['Collect the .whl package', 'Navigate through Heights', 'Drop at the pip install point'],
        waypoints: [
            { id: 'wp-pypi-1', label: 'Collect Package', position: [-45, 0.5, 20], radius: 4, order: 0 },
            { id: 'wp-pypi-2', label: 'Navigate Heights', position: [-25, 0.5, 35], radius: 4, order: 1 },
            { id: 'wp-pypi-3', label: 'PIP Install Point', position: [-15, 0.5, 40], radius: 4, order: 2 },
        ],
    },

    // === ESCAPE MISSIONS ===
    {
        id: 'm-escape-test-drones',
        title: 'Test Suite Pursuit',
        description: 'You broke 47 tests. The CI drones are swarming. Run through React District and reach the safe house before coverage drops to zero.',
        type: 'escape',
        districtId: 'react-district',
        difficulty: 3,
        timeLimit: 30,
        reward: 200,
        factionReward: 15,
        status: 'available',
        objectives: ['Evade test drones', 'Reach the safe house', 'Survive for 30 seconds'],
        waypoints: [
            { id: 'wp-escape-r1', label: 'Escape Start', position: [-45, 0.5, -45], radius: 4, order: 0 },
            { id: 'wp-escape-r2', label: 'Safe House', position: [-15, 0.5, -20], radius: 5, order: 1 },
        ],
    },
    {
        id: 'm-escape-test-drones-linux',
        title: 'Kernel Panic Escape',
        description: 'Something went wrong deep in the Underground. Segfaults are spreading. Get out before the whole system locks.',
        type: 'escape',
        districtId: 'linux-underground',
        difficulty: 4,
        timeLimit: 25,
        reward: 300,
        factionReward: 20,
        status: 'available',
        objectives: ['Navigate collapsing tunnels', 'Avoid segfault zones', 'Reach surface exit'],
        waypoints: [
            { id: 'wp-kernel-1', label: 'Deep Tunnel', position: [-5, 0.5, 55], radius: 4, order: 0 },
            { id: 'wp-kernel-2', label: 'Segfault Bypass', position: [8, 0.5, 65], radius: 4, order: 1 },
            { id: 'wp-kernel-3', label: 'Surface Exit', position: [0, 0.5, 75], radius: 5, order: 2 },
        ],
    },

    // === RECOVERY MISSIONS ===
    {
        id: 'm-recover-artifact-rust',
        title: 'Cargo Heist: Lost Crate',
        description: 'A critical build artifact went missing in the Rust Docks. Find the corrupted crate, decrypt it, and bring it back.',
        type: 'recovery',
        districtId: 'rust-docks',
        difficulty: 3,
        timeLimit: 50,
        reward: 250,
        factionReward: 15,
        status: 'available',
        objectives: ['Locate the lost crate', 'Decrypt the artifact', 'Return to base'],
        waypoints: [
            { id: 'wp-cargo-1', label: 'Search Area', position: [20, 0.5, -35], radius: 5, order: 0 },
            { id: 'wp-cargo-2', label: 'Lost Crate', position: [40, 0.5, -45], radius: 4, order: 1 },
            { id: 'wp-cargo-3', label: 'Docks Base', position: [30, 0.5, -25], radius: 4, order: 2 },
        ],
    },
    {
        id: 'm-recover-artifact-linux',
        title: 'Root Access Recovery',
        description: 'Someone dropped a root key deep in the Underground. Retrieve it before the wrong faction gets their hands on it.',
        type: 'recovery',
        districtId: 'linux-underground',
        difficulty: 5,
        timeLimit: 40,
        reward: 400,
        factionReward: 25,
        status: 'available',
        objectives: ['Descend to kernel level', 'Find the root key', 'Extract without detection'],
        waypoints: [
            { id: 'wp-root-1', label: 'Tunnel Entrance', position: [5, 0.5, 50], radius: 4, order: 0 },
            { id: 'wp-root-2', label: 'Root Key Location', position: [-8, 0.5, 70], radius: 4, order: 1 },
            { id: 'wp-root-3', label: 'Extraction Point', position: [0, 0.5, 48], radius: 5, order: 2 },
        ],
    },

    // === DEFENSE MISSIONS ===
    {
        id: 'm-defend-terminal-rust',
        title: 'Hold the Build Server',
        description: 'Fork gangs are trying to overwrite the Rust Docks build config. Hold position at the terminal until compilation completes.',
        type: 'defense',
        districtId: 'rust-docks',
        difficulty: 3,
        timeLimit: 35,
        reward: 200,
        factionReward: 12,
        status: 'available',
        objectives: ['Reach the build terminal', 'Defend for 35 seconds', 'Keep compile progress above 50%'],
        waypoints: [
            { id: 'wp-defend-r1', label: 'Build Terminal', position: [35, 0.5, -30], radius: 5, order: 0 },
        ],
    },
    {
        id: 'm-defend-terminal-go',
        title: 'Freeway Tollbooth Defense',
        description: 'The Go Freeway tollbooth is under attack. Keep the goroutines running and the channels open.',
        type: 'defense',
        districtId: 'go-freeway',
        difficulty: 2,
        timeLimit: 40,
        reward: 175,
        factionReward: 10,
        status: 'available',
        objectives: ['Guard the tollbooth', 'Keep connection channels open', 'Repel attackers'],
        waypoints: [
            { id: 'wp-defend-g1', label: 'Tollbooth', position: [25, 0.5, 35], radius: 5, order: 0 },
        ],
    },

    // === SPECIAL MISSIONS ===
    {
        id: 'm-smuggle-hotfix',
        title: 'Hotfix Smuggler',
        description: 'CI/CD checkpoints are everywhere in Python Heights. Sneak a critical hotfix through without triggering the pipeline.',
        type: 'delivery',
        districtId: 'python-heights',
        difficulty: 3,
        timeLimit: 35,
        reward: 225,
        factionReward: 18,
        status: 'available',
        objectives: ['Receive the hotfix', 'Avoid CI checkpoints', 'Deploy to production'],
        waypoints: [
            { id: 'wp-hotfix-1', label: 'Hotfix Source', position: [-40, 0.5, 25], radius: 4, order: 0 },
            { id: 'wp-hotfix-2', label: 'CI Bypass', position: [-25, 0.5, 40], radius: 4, order: 1 },
            { id: 'wp-hotfix-3', label: 'Prod Server', position: [-20, 0.5, 45], radius: 4, order: 2 },
        ],
    },
    {
        id: 'm-hijack-release',
        title: 'Release Train Heist',
        description: 'The TypeScript Terminal release train is leaving. Board it, override the version bump, and hijack the release notes.',
        type: 'recovery',
        districtId: 'typescript-terminal',
        difficulty: 4,
        timeLimit: 30,
        reward: 350,
        factionReward: 22,
        status: 'available',
        objectives: ['Board the release train', 'Override version bump', 'Hijack release notes'],
        waypoints: [
            { id: 'wp-train-1', label: 'Platform', position: [-8, 0.5, -65], radius: 4, order: 0 },
            { id: 'wp-train-2', label: 'Override Console', position: [5, 0.5, -55], radius: 4, order: 1 },
            { id: 'wp-train-3', label: 'Release Notes', position: [10, 0.5, -50], radius: 4, order: 2 },
        ],
    },
    {
        id: 'm-race-regression',
        title: 'Regression Race',
        description: 'A regression window is closing on the Go Freeway. Race across districts to patch it before the deadline.',
        type: 'escape',
        districtId: 'go-freeway',
        difficulty: 2,
        timeLimit: 45,
        reward: 175,
        factionReward: 12,
        status: 'available',
        objectives: ['Start at Freeway entrance', 'Race to regression point', 'Apply fix before window closes'],
        waypoints: [
            { id: 'wp-race-1', label: 'Freeway Entrance', position: [15, 0.5, 25], radius: 4, order: 0 },
            { id: 'wp-race-2', label: 'Regression Point', position: [40, 0.5, 40], radius: 4, order: 1 },
            { id: 'wp-race-3', label: 'Patch Zone', position: [45, 0.5, 45], radius: 5, order: 2 },
        ],
    },

    // === BOSS MISSIONS ===
    {
        id: 'm-boss-merge-react',
        title: 'BOSS: The Great React Merge',
        description: 'A massive merge conflict has erupted in React District. Face the conflict head-on and resolve it before the codebase implodes.',
        type: 'boss',
        districtId: 'react-district',
        difficulty: 4,
        timeLimit: 60,
        reward: 500,
        factionReward: 30,
        status: 'available',
        objectives: ['Enter the conflict zone', 'Resolve all conflict hunks', 'Merge successfully'],
        waypoints: [
            { id: 'wp-boss-react', label: 'Conflict Zone', position: [-30, 0.5, -30], radius: 5, order: 0 },
        ],
    },
    {
        id: 'm-boss-merge-ts',
        title: 'BOSS: TypeScript Type War',
        description: 'Two massive PRs collided at TypeScript Terminal. The types are fighting each other. Pick the right resolutions or the whole station crashes.',
        type: 'boss',
        districtId: 'typescript-terminal',
        difficulty: 5,
        timeLimit: 45,
        reward: 600,
        factionReward: 35,
        status: 'available',
        objectives: ['Enter Terminal conflict zone', 'Resolve type conflicts', 'Prevent station crash'],
        waypoints: [
            { id: 'wp-boss-ts', label: 'Terminal Conflict Zone', position: [0, 0.5, -60], radius: 5, order: 0 },
        ],
    },
];
