// ─── Fake Repo Snapshots ───
// Seed fixtures for Phase 1: repo-to-city translation without real GitHub auth.
// Each fixture represents a plausible repo structure with modules, deps, and signals.

import type { RepoModel } from '../repoModel';

/**
 * Fixture 1: A fullstack web app with frontend, worker API, shared types, docs, and infra.
 * Modeled loosely on a real-world Cloudflare Workers + Vite + React project.
 */
export const REPO_FIXTURE_FULLSTACK: RepoModel = {
  repoId: 'fake-fullstack-001',
  owner: 'acme-dev',
  name: 'launchpad',
  defaultBranch: 'main',
  visibility: 'public',
  archetype: 'fullstack',
  languages: [
    { name: 'TypeScript', bytes: 245_000, share: 0.62 },
    { name: 'CSS', bytes: 48_000, share: 0.12 },
    { name: 'JavaScript', bytes: 38_000, share: 0.10 },
    { name: 'HTML', bytes: 12_000, share: 0.03 },
    { name: 'JSON', bytes: 52_000, share: 0.13 },
  ],
  modules: [
    {
      id: 'mod-frontend',
      name: 'frontend',
      path: 'frontend/',
      kind: 'app',
      language: 'TypeScript',
      fileCount: 34,
      totalBytes: 142_000,
      importanceScore: 85,
      activityScore: 90,
      riskScore: 40,
    },
    {
      id: 'mod-worker',
      name: 'worker',
      path: 'worker/',
      kind: 'service',
      language: 'TypeScript',
      fileCount: 8,
      totalBytes: 62_000,
      importanceScore: 90,
      activityScore: 70,
      riskScore: 55,
    },
    {
      id: 'mod-shared',
      name: 'shared',
      path: 'shared/',
      kind: 'package',
      language: 'TypeScript',
      fileCount: 12,
      totalBytes: 28_000,
      importanceScore: 75,
      activityScore: 50,
      riskScore: 20,
    },
    {
      id: 'mod-docs',
      name: 'docs',
      path: 'docs/',
      kind: 'docs',
      language: null,
      fileCount: 9,
      totalBytes: 45_000,
      importanceScore: 30,
      activityScore: 60,
      riskScore: 5,
    },
    {
      id: 'mod-infra',
      name: 'infra',
      path: '.github/',
      kind: 'infra',
      language: null,
      fileCount: 5,
      totalBytes: 8_000,
      importanceScore: 60,
      activityScore: 25,
      riskScore: 35,
    },
    {
      id: 'mod-migrations',
      name: 'migrations',
      path: 'worker/migrations/',
      kind: 'folder',
      language: 'SQL',
      fileCount: 4,
      totalBytes: 6_000,
      importanceScore: 50,
      activityScore: 15,
      riskScore: 45,
    },
  ],
  dependencyEdges: [
    { fromModuleId: 'mod-frontend', toModuleId: 'mod-shared', weight: 0.9, reason: 'import' },
    { fromModuleId: 'mod-worker', toModuleId: 'mod-shared', weight: 0.85, reason: 'import' },
    { fromModuleId: 'mod-frontend', toModuleId: 'mod-worker', weight: 0.6, reason: 'service_link' },
    { fromModuleId: 'mod-worker', toModuleId: 'mod-migrations', weight: 0.7, reason: 'folder_reference' },
    { fromModuleId: 'mod-infra', toModuleId: 'mod-worker', weight: 0.5, reason: 'service_link' },
  ],
  signals: [
    {
      type: 'failing_workflow',
      target: 'mod-infra',
      severity: 3,
      title: 'Deploy workflow failing',
      detail: 'The production deploy workflow has failed 3 times in the last 24 hours.',
    },
    {
      type: 'merge_conflict',
      target: 'mod-frontend',
      severity: 4,
      title: 'Conflict in App.tsx',
      detail: 'Two open PRs modify the main application shell with incompatible changes.',
    },
    {
      type: 'open_pr',
      target: 'mod-worker',
      severity: 2,
      title: '5 open PRs on worker',
      detail: 'Multiple PRs are queued for the API layer, some with overlapping changes.',
    },
    {
      type: 'dependency_drift',
      target: 'mod-shared',
      severity: 2,
      title: 'Outdated shared deps',
      detail: 'Shared package dependencies are 3 minor versions behind.',
    },
    {
      type: 'stale_pr',
      target: 'mod-docs',
      severity: 1,
      title: 'Stale docs PR',
      detail: 'A documentation PR has been open for 45 days with no review.',
    },
    {
      type: 'flaky_tests',
      target: 'mod-frontend',
      severity: 3,
      title: 'Flaky smoke tests',
      detail: 'Browser smoke tests fail intermittently on CI.',
    },
  ],
  generatedAt: '2026-03-08T15:30:00Z',
};

/**
 * Fixture 2: A small utility library with src, tests, and minimal infra.
 * Represents the "library" archetype.
 */
export const REPO_FIXTURE_LIBRARY: RepoModel = {
  repoId: 'fake-library-001',
  owner: 'util-labs',
  name: 'tiny-schema',
  defaultBranch: 'main',
  visibility: 'public',
  archetype: 'library',
  languages: [
    { name: 'TypeScript', bytes: 68_000, share: 0.78 },
    { name: 'JavaScript', bytes: 12_000, share: 0.14 },
    { name: 'JSON', bytes: 7_000, share: 0.08 },
  ],
  modules: [
    {
      id: 'mod-src',
      name: 'src',
      path: 'src/',
      kind: 'package',
      language: 'TypeScript',
      fileCount: 14,
      totalBytes: 52_000,
      importanceScore: 95,
      activityScore: 80,
      riskScore: 30,
    },
    {
      id: 'mod-tests',
      name: 'tests',
      path: 'tests/',
      kind: 'tests',
      language: 'TypeScript',
      fileCount: 10,
      totalBytes: 24_000,
      importanceScore: 70,
      activityScore: 65,
      riskScore: 15,
    },
    {
      id: 'mod-examples',
      name: 'examples',
      path: 'examples/',
      kind: 'docs',
      language: 'TypeScript',
      fileCount: 3,
      totalBytes: 5_000,
      importanceScore: 25,
      activityScore: 20,
      riskScore: 5,
    },
    {
      id: 'mod-ci',
      name: 'ci',
      path: '.github/',
      kind: 'infra',
      language: null,
      fileCount: 2,
      totalBytes: 3_000,
      importanceScore: 45,
      activityScore: 10,
      riskScore: 20,
    },
  ],
  dependencyEdges: [
    { fromModuleId: 'mod-tests', toModuleId: 'mod-src', weight: 0.95, reason: 'import' },
    { fromModuleId: 'mod-examples', toModuleId: 'mod-src', weight: 0.7, reason: 'import' },
    { fromModuleId: 'mod-ci', toModuleId: 'mod-tests', weight: 0.4, reason: 'service_link' },
  ],
  signals: [
    {
      type: 'security_alert',
      target: 'mod-src',
      severity: 4,
      title: 'Prototype pollution risk',
      detail: 'A dependency has a known prototype pollution vulnerability.',
    },
    {
      type: 'issue_spike',
      target: 'mod-src',
      severity: 3,
      title: 'Issue spike on validation module',
      detail: '12 new issues filed in the last week about schema validation edge cases.',
    },
    {
      type: 'flaky_tests',
      target: 'mod-tests',
      severity: 2,
      title: 'Intermittent test failures',
      detail: 'Two tests timeout sporadically on slower CI runners.',
    },
  ],
  generatedAt: '2026-03-08T15:30:00Z',
};

/**
 * Fixture 3: A backend service repo with API, runtime, data, tests, and infra.
 * Represents the "backend" archetype.
 */
export const REPO_FIXTURE_BACKEND: RepoModel = {
  repoId: 'fake-backend-001',
  owner: 'ops-lab',
  name: 'event-hub',
  defaultBranch: 'main',
  visibility: 'private',
  archetype: 'backend',
  languages: [
    { name: 'TypeScript', bytes: 158_000, share: 0.56 },
    { name: 'SQL', bytes: 61_000, share: 0.22 },
    { name: 'JSON', bytes: 24_000, share: 0.08 },
    { name: 'YAML', bytes: 19_000, share: 0.07 },
    { name: 'Shell', bytes: 18_000, share: 0.07 },
  ],
  modules: [
    {
      id: 'mod-api',
      name: 'api',
      path: 'api/',
      kind: 'service',
      language: 'TypeScript',
      fileCount: 26,
      totalBytes: 96_000,
      importanceScore: 94,
      activityScore: 82,
      riskScore: 58,
    },
    {
      id: 'mod-jobs',
      name: 'jobs',
      path: 'server/jobs/',
      kind: 'service',
      language: 'TypeScript',
      fileCount: 11,
      totalBytes: 36_000,
      importanceScore: 72,
      activityScore: 64,
      riskScore: 41,
    },
    {
      id: 'mod-db',
      name: 'db',
      path: 'db/',
      kind: 'folder',
      language: 'SQL',
      fileCount: 15,
      totalBytes: 61_000,
      importanceScore: 87,
      activityScore: 53,
      riskScore: 49,
    },
    {
      id: 'mod-tests',
      name: 'tests',
      path: 'tests/',
      kind: 'tests',
      language: 'TypeScript',
      fileCount: 13,
      totalBytes: 29_000,
      importanceScore: 69,
      activityScore: 47,
      riskScore: 21,
    },
    {
      id: 'mod-infra',
      name: 'infra',
      path: '.github/',
      kind: 'infra',
      language: null,
      fileCount: 5,
      totalBytes: 9_000,
      importanceScore: 56,
      activityScore: 30,
      riskScore: 33,
    },
    {
      id: 'mod-docs',
      name: 'docs',
      path: 'docs/runbooks/',
      kind: 'docs',
      language: null,
      fileCount: 6,
      totalBytes: 12_000,
      importanceScore: 24,
      activityScore: 22,
      riskScore: 8,
    },
  ],
  dependencyEdges: [
    { fromModuleId: 'mod-api', toModuleId: 'mod-db', weight: 0.94, reason: 'service_link' },
    { fromModuleId: 'mod-jobs', toModuleId: 'mod-db', weight: 0.78, reason: 'service_link' },
    { fromModuleId: 'mod-tests', toModuleId: 'mod-api', weight: 0.88, reason: 'import' },
    { fromModuleId: 'mod-tests', toModuleId: 'mod-jobs', weight: 0.56, reason: 'import' },
    { fromModuleId: 'mod-infra', toModuleId: 'mod-api', weight: 0.48, reason: 'service_link' },
    { fromModuleId: 'mod-docs', toModuleId: 'mod-api', weight: 0.35, reason: 'folder_reference' },
  ],
  signals: [
    {
      type: 'failing_workflow',
      target: 'mod-infra',
      severity: 4,
      title: 'Prod deploy rollback loop',
      detail: 'The release workflow has rolled back twice after failed health checks.',
    },
    {
      type: 'security_alert',
      target: 'mod-db',
      severity: 4,
      title: 'Migration account over-scoped',
      detail: 'Database automation is using credentials with write access outside the migration role.',
    },
    {
      type: 'open_pr',
      target: 'mod-api',
      severity: 3,
      title: 'API queue backed up',
      detail: 'Seven API-layer pull requests are stacked behind an unresolved contract review.',
    },
    {
      type: 'flaky_tests',
      target: 'mod-tests',
      severity: 2,
      title: 'Contract suite timing out',
      detail: 'The integration suite flakes when job workers are under load.',
    },
    {
      type: 'dependency_drift',
      target: 'mod-jobs',
      severity: 2,
      title: 'Job runtime packages stale',
      detail: 'Background worker dependencies are lagging several patch releases.',
    },
  ],
  generatedAt: '2026-03-08T15:30:00Z',
};

/**
 * Fixture 4: A frontend-only UI repo with component surface, stories, assets, tests, and CI.
 * Represents the "frontend" archetype.
 */
export const REPO_FIXTURE_FRONTEND: RepoModel = {
  repoId: 'fake-frontend-001',
  owner: 'pixel-craft',
  name: 'signal-board',
  defaultBranch: 'main',
  visibility: 'public',
  archetype: 'frontend',
  languages: [
    { name: 'TypeScript', bytes: 154_000, share: 0.46 },
    { name: 'CSS', bytes: 78_000, share: 0.23 },
    { name: 'HTML', bytes: 38_000, share: 0.11 },
    { name: 'JavaScript', bytes: 24_000, share: 0.07 },
    { name: 'MDX', bytes: 26_000, share: 0.08 },
    { name: 'SVG', bytes: 15_000, share: 0.05 },
  ],
  modules: [
    {
      id: 'mod-ui',
      name: 'ui',
      path: 'src/ui/',
      kind: 'folder',
      language: 'TypeScript',
      fileCount: 28,
      totalBytes: 104_000,
      importanceScore: 93,
      activityScore: 86,
      riskScore: 34,
    },
    {
      id: 'mod-storybook',
      name: 'storybook',
      path: '.storybook/',
      kind: 'docs',
      language: 'MDX',
      fileCount: 12,
      totalBytes: 29_000,
      importanceScore: 58,
      activityScore: 49,
      riskScore: 17,
    },
    {
      id: 'mod-styles',
      name: 'styles',
      path: 'styles/',
      kind: 'folder',
      language: 'CSS',
      fileCount: 17,
      totalBytes: 43_000,
      importanceScore: 72,
      activityScore: 61,
      riskScore: 23,
    },
    {
      id: 'mod-assets',
      name: 'assets',
      path: 'assets/',
      kind: 'folder',
      language: 'SVG',
      fileCount: 14,
      totalBytes: 18_000,
      importanceScore: 49,
      activityScore: 38,
      riskScore: 14,
    },
    {
      id: 'mod-tests',
      name: 'tests',
      path: 'tests/',
      kind: 'tests',
      language: 'TypeScript',
      fileCount: 11,
      totalBytes: 21_000,
      importanceScore: 67,
      activityScore: 44,
      riskScore: 18,
    },
    {
      id: 'mod-infra',
      name: 'infra',
      path: '.github/',
      kind: 'infra',
      language: null,
      fileCount: 4,
      totalBytes: 5_000,
      importanceScore: 47,
      activityScore: 26,
      riskScore: 22,
    },
  ],
  dependencyEdges: [
    { fromModuleId: 'mod-ui', toModuleId: 'mod-styles', weight: 0.92, reason: 'import' },
    { fromModuleId: 'mod-ui', toModuleId: 'mod-assets', weight: 0.71, reason: 'import' },
    { fromModuleId: 'mod-storybook', toModuleId: 'mod-ui', weight: 0.84, reason: 'import' },
    { fromModuleId: 'mod-storybook', toModuleId: 'mod-styles', weight: 0.52, reason: 'import' },
    { fromModuleId: 'mod-tests', toModuleId: 'mod-ui', weight: 0.88, reason: 'import' },
    { fromModuleId: 'mod-infra', toModuleId: 'mod-tests', weight: 0.42, reason: 'service_link' },
  ],
  signals: [
    {
      type: 'open_pr',
      target: 'mod-ui',
      severity: 3,
      title: 'UI shell review queue stalled',
      detail: 'Four interface PRs are waiting on a final component contract review.',
    },
    {
      type: 'flaky_tests',
      target: 'mod-tests',
      severity: 2,
      title: 'Visual regression snapshots unstable',
      detail: 'Story-driven snapshots fail intermittently when asset loads race on CI.',
    },
    {
      type: 'dependency_drift',
      target: 'mod-storybook',
      severity: 2,
      title: 'Storybook addons lagging',
      detail: 'The component preview toolchain is several patch releases behind the UI baseline.',
    },
    {
      type: 'merge_conflict',
      target: 'mod-styles',
      severity: 3,
      title: 'Theme tokens conflicted',
      detail: 'Parallel work on shared tokens created overlapping color system changes.',
    },
    {
      type: 'failing_workflow',
      target: 'mod-infra',
      severity: 2,
      title: 'Preview deploy checks red',
      detail: 'The static preview pipeline is failing on bundle-size and asset manifest validation.',
    },
  ],
  generatedAt: '2026-03-08T15:30:00Z',
};

/**
 * Fixture 5: A workspace-style monorepo with apps, packages, services, and workspace control.
 * Represents the "monorepo" archetype.
 */
export const REPO_FIXTURE_MONOREPO: RepoModel = {
  repoId: 'fake-monorepo-001',
  owner: 'workspace-labs',
  name: 'orbit-stack',
  defaultBranch: 'main',
  visibility: 'public',
  archetype: 'monorepo',
  languages: [
    { name: 'TypeScript', bytes: 286_000, share: 0.63 },
    { name: 'CSS', bytes: 31_000, share: 0.07 },
    { name: 'JSON', bytes: 42_000, share: 0.09 },
    { name: 'YAML', bytes: 28_000, share: 0.06 },
    { name: 'MDX', bytes: 34_000, share: 0.08 },
    { name: 'Shell', bytes: 31_000, share: 0.07 },
  ],
  modules: [
    {
      id: 'mod-web',
      name: 'web',
      path: 'apps/web/',
      kind: 'app',
      language: 'TypeScript',
      fileCount: 31,
      totalBytes: 112_000,
      importanceScore: 92,
      activityScore: 88,
      riskScore: 43,
    },
    {
      id: 'mod-admin',
      name: 'admin',
      path: 'apps/admin/',
      kind: 'app',
      language: 'TypeScript',
      fileCount: 22,
      totalBytes: 74_000,
      importanceScore: 79,
      activityScore: 63,
      riskScore: 36,
    },
    {
      id: 'mod-auth',
      name: 'auth',
      path: 'services/auth/',
      kind: 'service',
      language: 'TypeScript',
      fileCount: 16,
      totalBytes: 49_000,
      importanceScore: 84,
      activityScore: 71,
      riskScore: 47,
    },
    {
      id: 'mod-ui-kit',
      name: 'ui-kit',
      path: 'packages/ui-kit/',
      kind: 'package',
      language: 'TypeScript',
      fileCount: 19,
      totalBytes: 58_000,
      importanceScore: 86,
      activityScore: 54,
      riskScore: 19,
    },
    {
      id: 'mod-config',
      name: 'config',
      path: 'packages/config/',
      kind: 'package',
      language: 'TypeScript',
      fileCount: 9,
      totalBytes: 18_000,
      importanceScore: 66,
      activityScore: 37,
      riskScore: 14,
    },
    {
      id: 'mod-workspace',
      name: 'workspace',
      path: 'pnpm-workspace.yaml',
      kind: 'control',
      language: 'YAML',
      fileCount: 3,
      totalBytes: 4_000,
      importanceScore: 63,
      activityScore: 28,
      riskScore: 20,
    },
    {
      id: 'mod-e2e',
      name: 'e2e',
      path: 'tests/e2e/',
      kind: 'tests',
      language: 'TypeScript',
      fileCount: 8,
      totalBytes: 16_000,
      importanceScore: 61,
      activityScore: 45,
      riskScore: 22,
    },
    {
      id: 'mod-docs',
      name: 'docs',
      path: 'docs/',
      kind: 'docs',
      language: 'MDX',
      fileCount: 7,
      totalBytes: 19_000,
      importanceScore: 27,
      activityScore: 23,
      riskScore: 7,
    },
  ],
  dependencyEdges: [
    { fromModuleId: 'mod-web', toModuleId: 'mod-ui-kit', weight: 0.93, reason: 'import' },
    { fromModuleId: 'mod-web', toModuleId: 'mod-config', weight: 0.78, reason: 'import' },
    { fromModuleId: 'mod-web', toModuleId: 'mod-auth', weight: 0.66, reason: 'service_link' },
    { fromModuleId: 'mod-admin', toModuleId: 'mod-ui-kit', weight: 0.88, reason: 'import' },
    { fromModuleId: 'mod-admin', toModuleId: 'mod-config', weight: 0.74, reason: 'import' },
    { fromModuleId: 'mod-admin', toModuleId: 'mod-auth', weight: 0.58, reason: 'service_link' },
    { fromModuleId: 'mod-auth', toModuleId: 'mod-config', weight: 0.62, reason: 'package_dependency' },
    { fromModuleId: 'mod-e2e', toModuleId: 'mod-web', weight: 0.72, reason: 'import' },
    { fromModuleId: 'mod-e2e', toModuleId: 'mod-auth', weight: 0.54, reason: 'import' },
    { fromModuleId: 'mod-workspace', toModuleId: 'mod-web', weight: 0.46, reason: 'folder_reference' },
    { fromModuleId: 'mod-workspace', toModuleId: 'mod-admin', weight: 0.44, reason: 'folder_reference' },
    { fromModuleId: 'mod-workspace', toModuleId: 'mod-auth', weight: 0.41, reason: 'folder_reference' },
    { fromModuleId: 'mod-docs', toModuleId: 'mod-web', weight: 0.38, reason: 'folder_reference' },
  ],
  signals: [
    {
      type: 'open_pr',
      target: 'mod-web',
      severity: 3,
      title: 'Web app review queue piling up',
      detail: 'Five UI pull requests are stacked behind a shared design review.',
    },
    {
      type: 'security_alert',
      target: 'mod-auth',
      severity: 4,
      title: 'Auth token validation gap',
      detail: 'A shared auth dependency is missing strict audience validation on one flow.',
    },
    {
      type: 'dependency_drift',
      target: 'mod-config',
      severity: 2,
      title: 'Workspace configs out of sync',
      detail: 'Multiple package build configs are drifting from the workspace baseline.',
    },
    {
      type: 'failing_workflow',
      target: 'mod-workspace',
      severity: 3,
      title: 'Workspace pipeline unstable',
      detail: 'The monorepo build pipeline is failing on cached package graph resolution.',
    },
    {
      type: 'flaky_tests',
      target: 'mod-e2e',
      severity: 3,
      title: 'Cross-app E2E suite flaky',
      detail: 'End-to-end tests intermittently fail when both apps deploy in parallel.',
    },
  ],
  generatedAt: '2026-03-08T15:30:00Z',
};

export const REPO_FIXTURES: RepoModel[] = [
  REPO_FIXTURE_FULLSTACK,
  REPO_FIXTURE_LIBRARY,
  REPO_FIXTURE_BACKEND,
  REPO_FIXTURE_FRONTEND,
  REPO_FIXTURE_MONOREPO,
];
